### ISSUE TITLE
Safari can't load any data from this location

### ISSUE THREAD

**Issue by sblommers** [vaadin/bakery-app-starter-issues#11]
"Safari can't open the page because Safari can't load any data from this location"

go to https://bakery-flow.demo.vaadin.com/ with a clean safari browser (no cache/cookies/history of bakery app). After a refresh the page does work but as soon as you clear history and go to the bakery app you get this error.

Any ideas?

**Comment by johannesh2** [comment]
Could you give more details on the steps to reproduce. I tried a few times differently with Safari 11 and 10 and wasn't able to reproduce this.

**Comment by sblommers** [comment]
We are not able to reproduce this any more, perhaps something unrelated to Vaadin, I'm closing this. Sorry for taking some of your time.

**Comment by johannesh2** [comment]
No problem. Thank you for fast response.
