### ISSUE TITLE
Uncaught ReferenceError: Polymer is not defined

### ISSUE THREAD

**Issue by Jakasil** [vaadin/bakery-app-starter-issues#2]
![flow-error](https://user-images.githubusercontent.com/15026044/36138711-7833ecec-10d5-11e8-8027-a22052ca897a.png)

[eclipse-console.txt](https://github.com/vaadin/bakery-app-starter-issues/files/1719057/eclipse-console.txt)

**Comment by johannesh2** [comment]
Which vaadin.version you are using in pom.xml?

**Comment by sblommers** [comment]
In his eclipse-console it says 10.0.0.alpha15 but downloading the starter-app it still uses 10.0.0.alpha13, i'll try and reproduce with 10.0.0.alpha15

**Comment by johannesh2** [comment]
Latest release available from vaadin.com/start is now using 10.0.0.alpha21. Please reopen if this is still happening.
