### ISSUE TITLE
Clicking on empty space unexpectedly causes editor to pop up

### ISSUE THREAD

**Issue by mstahv** [vaadin/bakery-app-starter-issues#6]
<img width="1181" alt="screen shot 2018-03-14 at 11 36 08" src="https://user-images.githubusercontent.com/1478052/37394410-5ae95c54-277c-11e8-87fd-e9e52237d752.png">

**Comment by manolo** [comment]
That is intentional, since that is part of the grid row. 
It can be easily fixed by adapting grid width to the card width, but then grid scroller is moved from window border and looks odd

**Comment by mstahv** [comment]
Sure, it may work as coded, but it doesn't work as user expects it to work ;-)

**Comment by manolo** [comment]
What I meant, is that fixing one issue produces another one, and fixing both needs some workaround.
This sort of workarounds in an application that tries to demonstrate simplicity can make the user distract on certain code that it's not relevant.

**Comment by johannesh2** [comment]
I agree the clicking behavior currently is confusing. Code should be kept simple so no workarounds please. Making the grid width same as card width would solve the clicking issue and make it more consistent, event though it causes scroll wheel scrolling working only when you mouse-over grid.

**Comment by alexberazouski** [comment]
Was fixed. Check the latest version at http://vaadin.com/start
