### ISSUE TITLE
Can't login with Firefox

### ISSUE THREAD

**Issue by edler-san** [vaadin/bakery-app-starter-issues#7]
After having downloaded the Vaadin Bakery App Starter for Vaadin Framework 8 and Java EE and having started it via mvn wildfly:run I tested with Chrome, Safari and Firefox under Mac. Both Chrome and Safari work perfectly yet with Firefox (59.0) I can't get past the login screen. Whenever I click 'sign in' it simply deletes the entered credentials and nothing happens. I disabled all add-ons in Firefox and the problem persists.

**Comment by johannesh2** [comment]
Are you using JDK9?

**Comment by edler-san** [comment]
java version "1.8.0_131"

**Comment by johannesh2** [comment]
Thanks. I have hard time to get it reproduced.

**Comment by johannesh2** [comment]
Still can't reproduce this. Only odd behavior I noticed was with a request to /favicon.ico after login causing error, that goes away by refreshing. Still couldn't reproduce the "nothing happens after login". #8 is definitely an issue and happens only with JavaEE version.

**Comment by edler-san** [comment]
Deleting cookies solved the problem. Closing.
