### ISSUE TITLE
Faulty redirecting upon login/logout

### ISSUE THREAD

**Issue by edler-san** [vaadin/bakery-app-starter-issues#8]
I am using the Vaadin Bakery App Starter for Vaadin Framework 8 and Java EE.

If I login, logout and login again then URL fragment is appended once again, e.g. http://localhost:8080/#!dashboard#!dashboard causing a java.net.URISyntaxException: Illegal character in fragment at index 33: http://localhost:8080/#!dashboard#!dashboard

System is Windows 10, Browser is Firefox 59.

This is likely related to [https://github.com/vaadin/bakery-app-starter-issues/issues/7](url)

**Comment by johannesh2** [comment]
I was able to get Firefox working with replacing the init function from line 27 in src/main/webapp/login.html with this one
```java
    var init = function() {
      var theform = document.getElementById("theform");
      if (window.location.hash && theform.action.substr(-window.location.hash.length) != window.location.hash) {
        theform.action += window.location.hash;
      }
      if (window.location.search.indexOf("error")>0) {
          document.body.className = "error";
      }
    }
```

**Comment by johannesh2** [comment]
I'll release a new version of the starter later this week (maybe tomorrow)

**Comment by johannesh2** [comment]
I was able to fix this by latest FW8 version and using PushStateNavigation. I will release more likely that version. So with old bakery, the workaround provided here is relevant. Newer will not contain #! anymore.

**Comment by johannesh2** [comment]
This was fixed on Apr 20 in vaadin.com/start
